name: Build and test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript groff libbz2-dev zlib1g-dev

    - name: Configure
      run: |
        ./autogen.sh
        ./configure CFLAGS="-O2" CXXFLAGS="-O2"

    - name: Build
      run: |
        JOBS=$(nproc 2>/dev/null || echo 1)
        make ARFLAGS="cr" -j$JOBS

    - name: Install tests
      run: |
        git clone https://github.com/frederic-mahe/vsearch-tests

    - name: Run tests
      run: |
        export PATH=$PWD/bin:$PATH
        cd vsearch-tests
        bash ./run_all_tests.sh
